export const GIFS_REQUEST = "GIFS_REQUEST";
export const GIFS_REQUEST_SUCCESS = "GIFS_REQUEST_SUCCESS";
export const GIFS_REQUEST_FAILURE = "GIFS_REQUEST_FAILURE";
export const RESIZE_LAYOUT = "RESIZE_LAYOUT";
